### ISSUE TITLE
Compositors get segmentation fault after closing program

### ISSUE THREAD

**Issue by BachoSeven** [calculon102/xgifwallpaper#2]
Hi again! I played around with it a bit more, and although compositing works fine while `xgifwallpaper` is still running, if I close (ctrl+c) what happens is:
- The last fram stays on the root window(this is okay, resetting black root window would be worse imo)
- If I then try to close and re-open `picom` (my compositor), it gives me a segfault. I also tried running `xcompgr`, similar bad things happen:
```error 9: BadDrawable (invalid Pixmap or Window parameter) request 139 minor 4 serial 199
error 143: BadPicture request 139 minor 8 serial 200
error 143: BadPicture request 139 minor 8 serial 227
error 143: BadPicture request 139 minor 8 serial 244
error 143: BadPicture request 139 minor 8 serial 261
error 143: BadPicture request 139 minor 8 serial 278
```
(truncated)

**Comment by calculon102** [comment]
Thanks for the report! I can reproduce this. Think, I forgot to remove the atoms on the X server on exit, referencing to the root-pixmap for compositors, which they try to access for transparency. I'll look into this.

As for leaving the last frame after exit, it's just the most easy thing to do. As for an alternate strategy, I'm not sure, if it would even be possible to preserve the previous background in some fail-safe way. I would leave it as is for the moment, waiting for good ideas and feature requests.

**Comment by calculon102** [comment]
Problem was as expected and could be fixed. Actually, this makes the compositor clear the background on exit. If the compositors quits itself, the "true" root-window and its background will be visible. That will still be the last rendered GIF-frame.

**Comment by BachoSeven** [comment]
Thanks for the quick fix!

What I experience now on exiting `xgifwallpaper` is:

- `picom` quits forcibly because of it, this was not the case before (`xcompmgr does not, though).

- The original issue is fixed in the sense that I am able to restart `picom`; however, when I do so the root-window is reset, i.e. the last-rendered GIF-frame disappears leaving
  a black root window.
  Note that if I then close `picom` again, the GIF-frame is restored. I think it would be better to set that last GIF frame as the actuall wallpaper in a stable way somehow.

For comparison, using my script which basically is:
``` sh
xwinwrap -ov -ni -s -nf -- gifview -w WID $1 -a --no-interactive
```
the behaviour on exiting the script is:
- `picom` does not crash
- closing `picom` does not delete the last GIF-frame (closing `xcompgmr` does though)

  Let me know what you think of this

**Comment by calculon102** [comment]
I can't reproduce the forced exit of picom. Both `picom` and `xcompmgr` run stable and show a black (or dark gray) background. Which version of picom do you run? Any parameters?

The actual behavior with a running compositor (dark background, no image) is expected, after this fix. The image would have to stay in the shared memory-block after exit of `xgifwallpaper`, which I fear would essentially be a memory-leak. 

Without a compositor the "true" background of the root window is shown (again). This is drawn one time and would have to be removed in another way (just overdrawn).

For the moment, I think, the best way would to be consistent in both scenarios, with or without compositor. Which means, also erasing the background-image without compositor, reset the background to a solid color.

**Comment by BachoSeven** [comment]
Yea I also think that preserving the image would not be so desirable after all.

With regards to my version of `picom`, I use very experimental settings so maybe not representative of actual behaviour. I also use the `picom-ibhagwan-git` fork from AUR.
