### ISSUE TITLE
Crash when use --scale option

### ISSUE THREAD

**Issue by anaissls** [calculon102/xgifwallpaper#3]
The program crashes on openbox when I try to use the `--scale` option:
```
ivy@t480: ~ $ xgifwallpaper --scale FILL tumblr_np90omeRF31ripbvlo1_500.gif
thread 'main' panicked at 'Empty step in animation: UnexpectedEndOfFile', src/main.rs:238:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm using [this image](https://31.media.tumblr.com/5e2be2951c2504779065607305b15d42/tumblr_np90omeRF31ripbvlo1_500.gif).

**Comment by calculon102** [comment]
Thank you for your report!

~I can reproduce this. This problem is independent of Openbox, but seems to be rooted in the characteristics of this GIF.~

I could not reproduce this, with the latest build of 0.3 and with this specific GIF.

Does `xgifwallpaper` work with other GIFs for you?
If you download the mentioned GIF, is it rendered correctly in other programs, like when openend locally with Firefox?

**Comment by calculon102** [comment]
@Suguivy,  which version of `xgifwallpaper` did you use? See output of `xgifwallpaper -V`.

**Comment by anaissls** [comment]
I am using `xgifwallpaper 0.3.0` (compiled from the AUR).

I have my laptop screen and a second monitor and I have noticed that **the program crases when I am using both of them** and the `MAX` and `FILL` options in `--size`, but it doesnt using `--size NONE`.

If I only use my laptop screen there is not any problem using `--size FILL`.

Is the same behaviour with other GIFs, and the GIF I have used is rendered correctly in other programs.

~~I am thinking if the problem is that my two screens are overlapped...~~

**Comment by anaissls** [comment]
> I am thinking if the problem is that my two screens are overlapped...

This is not the problem, with my two screens not overlapping the program still crashes.

Also, if use the program with my screens overlaped (my screens have different size), the background shows also overlapped:
![](https://i.ibb.co/Ms462xp/Captura-de-pantalla-2020-11-29-14-31-24.png)

**Comment by calculon102** [comment]
Thank your very much for your specific information and testing. That was very helpful.
I could determine the problem and create a fix.
Are you able to compile this directly from this repository for a test, before I publish the fix on AUR?

**Comment by anaissls** [comment]
It works now with the last GIF but I have tested other GIFs and some of them are rendered in a some weird manner, like this (I am using two screens now):
![](https://i.ibb.co/nBkwczY/Captura-de-pantalla-2020-11-29-19-02-17.png)

I have used [this](https://github.com/thomas10-10/foo-Wallpaper-Feh-Gif/blob/master/gif/pixel.gif) GIF.

**Comment by calculon102** [comment]
Thank you, again. I created #4 to tackle this problem.
