### ISSUE TITLE
Upscaling of pixel-art GIFs renders glitches

### ISSUE THREAD

**Issue by calculon102** [calculon102/xgifwallpaper#4]
It works now with the last GIF but I have tested other GIFs and some of them are rendered in a some weird manner, like this (I am using two screens now):
![](https://i.ibb.co/nBkwczY/Captura-de-pantalla-2020-11-29-19-02-17.png)

I have used [this](https://github.com/thomas10-10/foo-Wallpaper-Feh-Gif/blob/master/gif/pixel.gif) GIF.

_Originally posted by @Suguivy in https://github.com/calculon102/xgifwallpaper/issues/3#issuecomment-735433214_

**Comment by calculon102** [comment]
@Suguivy, could you try again, if this fix works for you?

It should work out-of-the-box, due to a change in the order of the render-pipeline.
If that fails, there is a new option `scale-filter` (experimental). The value `PIXEL` is best suited for pixel-art and also a bit faster.

Thank you!

**Comment by anaissls** [comment]
It seems to work perfectly fine now :)
But just as you said, pixel backgrounds look better with the `--scale-filter` option.
Thank you for the fixes!
